name: Discord Announcements
on:
  release:
    types: [published]

permissions: {}

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    env:
      AVATAR_URL: "https://cdn.discordapp.com/icons/1165274913624572014/05a538c8bbb0d5da3b3755f5ba1ca32a.png"
    steps:
      - name: Release to Discord
        if: ${{ !github.event.release.prerelease }}
        uses: SethCohen/github-releases-to-discord@24d166886aee4646d448c8a389ff9e1ebcab3682 # v1.20.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "5763719"
          username: "Release Changelog"
          avatar_url: ${{ env.AVATAR_URL }}
          reduce_headings: true

      - name: Prerelease to Discord
        if: ${{ github.event.release.prerelease }}
        uses: SethCohen/github-releases-to-discord@24d166886aee4646d448c8a389ff9e1ebcab3682 # v1.20.0
        with:
          webhook_url: ${{ secrets.PRERELEASE_WEBHOOK_URL }}
          color: "15105570"
          username: "Prerelease Changelog"
          avatar_url: ${{ env.AVATAR_URL }}
          reduce_headings: true
